name: Rust build & test develop branch
permissions: read-all
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Install trunk
        run: curl https://get.trunk.io -fsSL | bash
      - name: Run trunk linting pass
        run: trunk check
      - name: Build cargo
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
